version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "GHA CI"
    groups:
      GHA_CI-dependency-update:
        patterns:
          - "*"
    labels:
      - "CI"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pre-commit"
    directory: "/"
    commit-message:
      prefix: "GHA CI"
    groups:
      GHA_CI-dependency-update:
        patterns:
          - "*"
    labels:
      - "CI"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/src/webui/www"
    commit-message:
      prefix: "WebUI"
    labels:
      - "WebUI"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/src/searchengine/nova3"
    commit-message:
      prefix: "Python"
    labels:
      - "CI"
    schedule:
      interval: "monthly"
